---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

```{r}
library(acs)
library(tigris)
library(dplyr)
library(leaflet)
library(stringr)
library(htmltools)
```

```{r}
med.age.merge.12 <-geo_join(tracts, medAge12, "GEOID", "GEOID")
med.age.merge.12 <- med.age.merge.12[med.age.merge.12$ALAND>0,]

med.age.merge.15 <-geo_join(tracts, medAge15, "GEOID", "GEOID")
med.age.merge.15 <- med.age.merge.15[med.age.merge.15$ALAND>0,]
```




```{r}
key <- insert key here

tracts <- tracts(state = "DC")
```

```{r}
api.key.install(key = key)


geo <- geo.make(state = 11, county = 1, tract = "*")

median.age <- acs.fetch(endyear = 2009, span = 5, geography = geo, table.number = "B01002", col.names = "pretty")

names(attributes(median.age))

attr(median.age, "acs.colnames")

med.age.df <- data.frame(paste0(str_pad(median.age@geography$state, 2, "left", pad = "0"),
                                        str_pad(median.age@geography$county, 3, "left", pad = "0"),
                                        str_pad(median.age@geography$tract, 6, "left", pad = "0")),
                         median.age@estimate[,c("Median Age by Sex: Median age -- Total:")], median.age@standard.error[,c("Median Age by Sex: Median age -- Total:")],
                         stringsAsFactors = FALSE)


rownames(med.age.df) <- 1:nrow(med.age.df)   
colnames(med.age.df) <- c("GEOID", "medianAge09", "stdErr")
```

```{r}
api.key.install(key = key)


```


```{r}
milennials.merge <- geo_join(tracts, milennials, "GEOID", "Id2")
med.age.merge <- geo_join(tracts, med.age.df, "GEOID", "GEOID")

med.age.merge <- med.age.merge[med.age.merge$ALAND>0,]

milennials09.merge <- geo_join(tracts, milennials09, "GEOID", "Id2")

millenials12.merge <- geo_join(tracts, millenials12, "GEOID", "Id2")

total_millennials.merge <- geo_join(tracts, total_millennials, "GEOID", "Id2")
```


```{r}
popup2 <- paste0("25 - 29 years old: ", milennials.merge$Total..Estimate..AGE...25.to.29.years, "%", "<br>", "Margin of error: ", milennials.merge$Total..Margin.of.Error..AGE...25.to.29.years, "<br>", "30 - 34 years old: ", milennials.merge$Total..Estimate..AGE...30.to.34.years, "%", "<br>", "Margin of error: ", milennials.merge$Total..Margin.of.Error..AGE...30.to.34.years)

labels2 <- sprintf(
  "<strong> %s percent </strong>", milennials.merge$summed
) %>% lapply(htmltools::HTML)

pal2 <- colorQuantile(palette = "YlGnBu", domain = milennials.merge$summed, n = 5)
  
m2 <- leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addMiniMap(
    tiles = providers$CartoDB.Positron,
    toggleDisplay = TRUE) %>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Full View",
    onClick=JS("function(btn, map){ map.setZoom(11); }"))) %>%
  addPolygons(data = milennials.merge,
              fillColor = ~pal2(milennials.merge$summed),
              fillOpacity = 0.6,
              weight = 0.2,
              smoothFactor = 0.2,
              popup = popup2,
              label = labels2,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",
                             padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"
              ),
              highlight = highlightOptions(
                weight = 3,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE
              )) %>%
  addLegend(pal = pal,
            values = milennials.merge$summed,
            position = "bottomright",
            title = "Percent 25-34<br>years old,<br>by census tract <br>(2015): ")
m2
```

```{r}
popup3 <- paste0("25 - 29 years old: ", milennials09.merge$Total..Estimate..Total.population...AGE...25.to.29.years, "%", "<br>", "Margin of error: ", milennials09.merge$NA., "<br>", "30 - 34 years old: ", milennials09.merge$total30to34Est, "%", "<br>", "Margin of error: ", milennials09.merge$Total..Margin.of.Error..Total.population...AGE...30.to.34.years)

labels3 <- sprintf(
  "<strong> %s percent </strong>", milennials09.merge$summed
) %>% lapply(htmltools::HTML)

pal3 <- colorQuantile(palette = "YlGnBu", domain = milennials09.merge$summed, n = 5)
  
m3 <- leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addMiniMap(
    tiles = providers$CartoDB.Positron,
    toggleDisplay = TRUE) %>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Full View",
    onClick=JS("function(btn, map){ map.setZoom(11); }"))) %>%
  addPolygons(data = milennials09.merge,
              fillColor = ~pal3(milennials09.merge$summed),
              fillOpacity = 0.6,
              weight = 0.2,
              smoothFactor = 0.2,
              popup = popup3,
              label = labels3,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",
                             padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"
              ),
              highlight = highlightOptions(
                weight = 3,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE
              )) %>%
  addLegend(pal = pal,
            values = milennials09.merge$summed,
            position = "bottomright",
            title = "Percent 25-34<br>years old,<br>by census tract<br>(2009): ")
m3
```

```{r}
popup4 <- paste0("25 - 29 years old: ", milennials12.merge$est25_29, "%", "<br>", "Margin of error: ", milennials12.merge$Total..Margin.of.Error..AGE...25.to.29.years, "<br>", "30 - 34 years old: ", milennials12.merge$est30_34, "%", "<br>", "Margin of error: ", milennials12.merge$Total..Margin.of.Error..AGE...30.to.34.years)

labels4 <- sprintf(
  "<strong> %s percent </strong>", milennials12.merge$summed
) %>% lapply(htmltools::HTML)

pal4 <- colorQuantile(palette = "YlGnBu", domain = milennials12.merge$summed, n = 5)
  
m4 <- leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addMiniMap(
    tiles = providers$CartoDB.Positron,
    toggleDisplay = TRUE) %>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Full View",
    onClick=JS("function(btn, map){ map.setZoom(11); }"))) %>%
  addPolygons(data = milennials12.merge,
              fillColor = ~pal4(milennials12.merge$summed),
              fillOpacity = 0.6,
              weight = 0.2,
              smoothFactor = 0.2,
              popup = popup3,
              label = labels4,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",
                             padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"
              ),
              highlight = highlightOptions(
                weight = 3,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE
              )) %>%
  addLegend(pal = pal,
            values = milennials12.merge$summed,
            position = "bottomright",
            title = "Percent 25-34<br>years old,<br>by census tract <br>(2012): ")
m4
```


```{r}
 make.map <- function(geoid, year, value) {
 popup <- paste0("GEOID: ", geoid, "<br>", "Median Age (", year, "):<br> ", value, " years old")
  
  pal <- colorNumeric(
    palette = "YlGnBu",
    domain = value)
    
leaflet() %>% 
    addProviderTiles("CartoDB.Positron") %>% 
    addPolygons(data = df,
                fillColor = ~pal(value),
                fillOpacity = 0.7,
                weight = 0.2,
                smoothFactor = 0.2,
                popup = popup) %>%
    addLegend(pal = pal,
              values = value,
              position = "bottomright",
              title = paste0("Median Age<br>", paste0(year, ":") ))
}
```




```{r}
#popup5 <- paste0("25 - 29 years old: ", milennials.merge$Total..Estimate..AGE...25.to.29.years, "%", "<br>", "Margin of error: ", milennials.merge$Total..Margin.of.Error..AGE...25.to.29.years, "<br>", "30 - 34 years old: ", milennials.merge$Total..Estimate..AGE...30.to.34.years, "%", "<br>", "Margin of error: ", milennials.merge$Total..Margin.of.Error..AGE...30.to.34.years)

labels5 <- sprintf(
  "<strong> %s points </strong>", round(total_millennials.merge$pctpt_diff, 2)
) %>% lapply(htmltools::HTML)

bin <- c(-30, -10, -5, 5, 10, 30)

pal <- colorBin(palette = "Spectral", domain = total_millennials.merge$pctpt_diff, bins = bin)
  
m5 <- leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addMiniMap(
    tiles = providers$CartoDB.Positron,
    toggleDisplay = TRUE) %>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Full View",
    onClick=JS("function(btn, map){ map.setZoom(11); }"))) %>%
  addPolygons(data = total_millennials.merge,
              fillColor = ~pal(total_millennials.merge$pctpt_diff),
              fillOpacity = 0.6,
              weight = 0.2,
              smoothFactor = 0.2,
              #popup = popup2,
              label = labels5,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal",
                             padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"
              ),
              highlight = highlightOptions(
                weight = 3,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE
              )) %>%
  addLegend(pal = pal,
            values = total_millennials.merge$pctpt_diff,
            position = "bottomright",
            title = "Percentage point<br>difference <br>in 25-34 yr old<b> population,<br>2009-2015,<br>by census tract")
m5
```

